// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA573NNJhQStxbsTST8BDo_eksVfPGwgjo',
    appId: '1:606183198176:web:aa50acba19ba7f97b66f85',
    messagingSenderId: '606183198176',
    projectId: 'clearchain-d52ee',
    authDomain: 'clearchain-d52ee.firebaseapp.com',
    storageBucket: 'clearchain-d52ee.firebasestorage.app',
    measurementId: 'G-YTCHS4SR9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsI4ZzvYoonJaLeW5WbQcKd64B3nUQdyQ',
    appId: '1:606183198176:android:8e932ec2099d805cb66f85',
    messagingSenderId: '606183198176',
    projectId: 'clearchain-d52ee',
    storageBucket: 'clearchain-d52ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLXUpZV9HbWK2uD8RX_-lbbTuIpQ_v62U',
    appId: '1:606183198176:ios:43b3a39c629974ebb66f85',
    messagingSenderId: '606183198176',
    projectId: 'clearchain-d52ee',
    storageBucket: 'clearchain-d52ee.firebasestorage.app',
    iosBundleId: 'com.example.testproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLXUpZV9HbWK2uD8RX_-lbbTuIpQ_v62U',
    appId: '1:606183198176:ios:43b3a39c629974ebb66f85',
    messagingSenderId: '606183198176',
    projectId: 'clearchain-d52ee',
    storageBucket: 'clearchain-d52ee.firebasestorage.app',
    iosBundleId: 'com.example.testproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA573NNJhQStxbsTST8BDo_eksVfPGwgjo',
    appId: '1:606183198176:web:9e3e10d38988fbe1b66f85',
    messagingSenderId: '606183198176',
    projectId: 'clearchain-d52ee',
    authDomain: 'clearchain-d52ee.firebaseapp.com',
    storageBucket: 'clearchain-d52ee.firebasestorage.app',
    measurementId: 'G-03V4QYFV29',
  );
}
